# Configuration for welcome - https://github.com/behaviorbot/welcome
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include steps to reproduce it.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ’– Thanks for opening this pull request! ğŸ’–

  Here is a list of things that will help get it across the finish line:

  - If this is a new or updated CSS interactive example, please ensure that you followed the [CSS styleguide](https://github.com/mdn/interactive-examples/blob/main/CSS-Example-Style-Guide.md)
  - If this is a new or updated JavaScript interactive example, please ensure that you followed the [JavaScript styleguide](https://github.com/mdn/interactive-examples/blob/main/JS-Example-Style-Guide.md)
  - If your changes affects any of the steps in our [contribution docs](https://github.com/mdn/interactive-examples/blob/main/CONTRIBUTING.md), please also make the relevant changes there.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰

# It is recommend to include as many gifs and emojis as possible
